"""Map Chinese location names to English for GBD data."""
import pandas as pd

# Chinese to English mapping for countries
# Based on common GBD location names
location_map = {
    "不丹": "Bhutan",
    "东帝汶民主共和国": "Timor-Leste",
    "中国": "China",
    "中非共和国": "Central African Republic",
    "丹麦": "Denmark",
    "乌克兰": "Ukraine",
    "乌兹别克斯坦": "Uzbekistan",
    "乌干达": "Uganda",
    "乌拉圭": "Uruguay",
    "乍得": "Chad",
    "也门": "Yemen",
    "亚美尼亚": "Armenia",
    "以色列": "Israel",
    "伊拉克": "Iraq",
    "伊朗伊斯兰共和国": "Iran",
    "伯利兹城": "Belize",
    "佛得角": "Cape Verde",
    "俄罗斯": "Russia",
    "保加利亚": "Bulgaria",
    "克罗地亚": "Croatia",
    "关岛": "Guam",
    "冈比亚": "Gambia",
    "冰岛": "Iceland",
    "几内亚": "Guinea",
    "几内亚比绍": "Guinea-Bissau",
    "刚果": "Congo",
    "刚果民主共和国": "Dem. Rep. Congo",
    "利比亚": "Libya",
    "利比里亚": "Liberia",
    "加拿大": "Canada",
    "加纳": "Ghana",
    "加蓬": "Gabon",
    "匈牙利": "Hungary",
    "北马其顿": "North Macedonia",
    "北马里亚纳群岛": "N. Mariana Islands",
    "南苏丹": "South Sudan",
    "南非": "South Africa",
    "博茨瓦纳": "Botswana",
    "卡塔尔": "Qatar",
    "卢旺达": "Rwanda",
    "卢森堡公国": "Luxembourg",
    "印度": "India",
    "印度尼西亚": "Indonesia",
    "危地马拉": "Guatemala",
    "厄瓜多尔": "Ecuador",
    "厄立特里亚国": "Eritrea",
    "古巴": "Cuba",
    "台湾": "Taiwan",
    "吉尔吉斯斯坦": "Kyrgyzstan",
    "吉布提": "Djibouti",
    "哈萨克斯坦": "Kazakhstan",
    "哥伦比亚": "Colombia",
    "哥斯达黎加": "Costa Rica",
    "喀麦隆": "Cameroon",
    "图瓦卢": "Tuvalu",
    "土库曼斯坦": "Turkmenistan",
    "土耳其": "Turkey",
    "圣卢西亚": "St. Lucia",
    "圣基茨和尼维斯": "St. Kitts and Nevis",
    "圣文森特和格林纳丁斯": "St. Vincent and the Grenadines",
    "圣多美和普林西比": "Sao Tome and Principe",
    "圣马力诺": "San Marino",
    "圭亚那": "Guyana",
    "坦桑尼亚联合共和国": "Tanzania",
    "埃及": "Egypt",
    "埃塞俄比亚": "Ethiopia",
    "基里巴斯": "Kiribati",
    "塔吉克斯坦": "Tajikistan",
    "塞尔维亚": "Serbia",
    "塞拉利昂": "Sierra Leone",
    "塞内加尔": "Senegal",
    "塞浦路斯": "Cyprus",
    "塞舌尔": "Seychelles",
    "墨西哥": "Mexico",
    "多哥": "Togo",
    "多米尼克": "Dominica",
    "多米尼加共和国": "Dominican Republic",
    "奥地利": "Austria",
    "委内瑞拉玻利瓦尔共和国": "Venezuela",
    "孟加拉国": "Bangladesh",
    "安哥拉": "Angola",
    "安提瓜和巴布达": "Antigua and Barbuda",
    "安圭拉": "Anguilla",
    "密克罗尼西亚联邦": "Federated States of Micronesia",
    "尼加拉瓜": "Nicaragua",
    "尼日利亚": "Nigeria",
    "尼日尔": "Niger",
    "尼泊尔": "Nepal",
    "巴布亚新几内亚": "Papua New Guinea",
    "巴拉圭": "Paraguay",
    "巴哈马": "Bahamas",
    "巴林": "Bahrain",
    "巴基斯坦": "Pakistan",
    "巴拿马": "Panama",
    "巴巴多斯": "Barbados",
    "希腊": "Greece",
    "格林纳达": "Grenada",
    "格陵兰": "Greenland",
    "格鲁吉亚": "Georgia",
    "比利时": "Belgium",
    "毛里塔尼亚": "Mauritania",
    "毛里求斯": "Mauritius",
    "汤加": "Tonga",
    "沙特阿拉伯": "Saudi Arabia",
    "波兰": "Poland",
    "法国": "France",
    "法属圭亚那": "French Guiana",
    "法属波利尼西亚": "French Polynesia",
    "波斯尼亚和黑塞哥维那": "Bosnia and Herzegovina",
    "泰国": "Thailand",
    "津巴布韦": "Zimbabwe",
    "洪都拉斯": "Honduras",
    "海地": "Haiti",
    "澳大利亚": "Australia",
    "爱尔兰": "Ireland",
    "爱沙尼亚": "Estonia",
    "牙买加": "Jamaica",
    "特立尼达和多巴哥": "Trinidad and Tobago",
    "玻利维亚多民族国": "Bolivia",
    "瑙鲁共和国": "Nauru",
    "瑞典": "Sweden",
    "瑞士": "Switzerland",
    "科威特": "Kuwait",
    "科特迪瓦": "Cote d'Ivoire",
    "科摩罗": "Comoros",
    "秘鲁": "Peru",
    "突尼斯": "Tunisia",
    "立陶宛": "Lithuania",
    "索马里": "Somalia",
    "约旦": "Jordan",
    "纳米比亚": "Namibia",
    "缅甸": "Myanmar",
    "老挝": "Laos",
    "肯尼亚": "Kenya",
    "芬兰": "Finnish",
    "苏丹": "Sudan",
    "苏里南": "Suriname",
    "萨尔瓦多": "El Salvador",
    "萨摩亚": "Samoa",
    "葡萄牙": "Portugal",
    "蒙古": "Mongolia",
    "孟加拉": "Bangladesh",
    "西班牙": "Spain",
    "摩尔多瓦共和国": "Moldova",
    "摩洛哥": "Morocco",
    "摩纳哥": "Monaco",
    "文莱达鲁萨兰国": "Brunei",
    "斐济": "Fiji",
    "斯威士兰": "Eswatini",
    "斯洛文尼亚": "Slovenia",
    "斯洛伐克": "Slovakia",
    "斯里兰卡": "Sri Lanka",
    "新加坡": "Singapore",
    "新西兰": "New Zealand",
    "日本": "Japan",
    "智利": "Chile",
    "朝鲜": "North Korea",
    "柬埔寨": "Cambodia",
    "格鲁吉亚": "Georgia",
    "意大利": "Italy",
    "越南": "Vietnam",
    "阿塞拜疆": "Azerbaijan",
    "阿富汗": "Afghanistan",
    "阿尔及利亚": "Algeria",
    "阿尔巴尼亚": "Albania",
    "阿拉伯叙利亚共和国": "Syria",
    "阿曼": "Oman",
    "阿根廷": "Argentina",
    "阿鲁巴": "Aruba",
    "马拉维": "Malawi",
    "马来西亚": "Malaysia",
    "马绍尔群岛": "Marshall Islands",
    "马达加斯加": "Madagascar",
    "马尔代夫": "Maldives",
    "马恩岛": "Isle of Man",
    "几内亚": "Guinea",
    "马里": "Mali",
    "黑山": "Montenegro",
    "美国": "United States",
    "美属维尔京群岛": "U.S. Virgin Islands",
    "美属萨摩亚群岛": "American Samoa",
    "赞比亚": "Zambia",
    "赤道几内亚": "Equatorial Guinea",
    "越南": "Vietnam",
    "利比亚": "Libya",
    "莱索托": "Lesotho",
    "菲律宾": "Philippines",
    "所罗门群岛": "Solomon Islands",
    "斯洛伐克": "Slovakia",
    "马其顿": "North Macedonia",
    "亚美尼亚": "Armenia",
    "阿联酋": "United Arab Emirates",
    "科索沃": "Kosovo",
    "纽埃": "Niue",
    "库克群岛": "Cook Islands",
    "托克劳群岛": "Tokelau",
    "诺福克岛": "Norfolk Island",
    "皮特凯恩群岛": "Pitcairn Islands",
    "圣赫勒拿": "St. Helena",
    "福克兰群岛": "Falkland Islands",
    "布韦岛": "Bouvet Island",
    "法属南部领地": "French Southern Territories",
    "赫德岛和麦克唐纳群岛": "Heard Island and McDonald Islands",
    "美属萨摩亚": "American Samoa",
    "蒙特塞拉特": "Montserrat",
    "圣皮埃尔和密克隆": "St. Pierre and Miquelon",
    "特克斯和凯科斯群岛": "Turks and Caicos Islands",
    "英属印度洋领地": "British Indian Ocean Territory",
    "波多黎各": "Puerto Rico",
    "开曼群岛": "Cayman Islands",
    "百慕大": "Bermuda",
    "直布罗陀": "Gibraltar",
    "马约特": "Mayotte",
    "留尼汪": "Reunion",
    "新喀里多尼亚": "New Caledonia",
    "瓦利斯和富图纳": "Wallis and Futuna",
    # Additional mappings for unmapped locations
    "圣卢西亚岛": "St. Lucia",
    "圣基茨和尼维斯联邦": "St. Kitts and Nevis",
    "圣多美和普林西比民主共和国": "Sao Tome and Principe",
    "圣马力诺共和国": "San Marino",
    "坦桑尼亚联合共和国": "Tanzania",
    "多米尼加岛": "Dominica",
    "大韩民国": "South Korea",
    "安道尔共和国": "Andorra",
    "巴勒斯坦": "Palestine",
    "巴林岛": "Bahrain",
    "玻利维亚国": "Bolivia",
    "特立尼达拉岛和多巴哥": "Trinidad and Tobago",
    "朝鲜民主主义人民共和国": "North Korea",
    "老挝人民民主共和国": "Laos",
    "摩纳哥公国": "Monaco",
    "委内瑞拉玻利瓦尔共和国": "Venezuela",
    "美利坚合众国": "United States",
    "阿拉伯联合酋长国": "United Arab Emirates",
    "阿拉伯叙利亚共和国": "Syria",
    "文莱达鲁萨兰国": "Brunei",
    "黑山共和国": "Montenegro",
    "科特廸亚": "Cote d'Ivoire",
    "帕劳共和国": "Palau",
    "瑙鲁共和国": "Nauru",
    "圣基茨和尼维斯": "St. Kitts and Nevis",
    "圣文森特和格林纳丁斯": "St. Vincent and the Grenadines",
    "厄立特里亚国": "Eritrea",
    "刚果民主共和国": "Dem. Rep. Congo",
    "伊朗伊斯兰共和国": "Iran",
    "东帝汶民主共和国": "Timor-Leste",
    "中非共和国": "Central African Republic",
    "几内亚比绍": "Guinea-Bissau",
    "博茨瓦纳": "Botswana",
    "土库曼斯坦": "Turkmenistan",
    "尼日利亚": "Nigeria",
    "巴布亚新几内亚": "Papua New Guinea",
    "希腊": "Greece",
    "德国": "Germany",
    "意大利": "Italy",
    "挪威": "Norway",
    "捷克共和国": "Czech Republic",
    "荷兰": "Netherlands",
    "英国": "United Kingdom",
    "法国": "France",
    "西班牙": "Spain",
    "葡萄牙": "Portugal",
    "瑞士": "Switzerland",
    "瑞典": "Sweden",
    "芬兰": "Finland",
    "丹麦": "Denmark",
    "比利时": "Belgium",
    "奥地利": "Austria",
    "波兰": "Poland",
    "匈牙利": "Hungary",
    "罗马尼亚": "Romania",
    "保加利亚": "Bulgaria",
    "希腊": "Greece",
    "克罗地亚": "Croatia",
    "斯洛文尼亚": "Slovenia",
    "斯洛伐克": "Slovakia",
    "立陶宛": "Lithuania",
    "拉脱维亚": "Latvia",
    "爱沙尼亚": "Estonia",
    "俄罗斯": "Russia",
    "乌克兰": "Ukraine",
    "白俄罗斯": "Belarus",
    "摩尔多瓦共和国": "Moldova",
    "塞尔维亚": "Serbia",
    "波斯尼亚和黑塞哥维那": "Bosnia and Herzegovina",
    "北马其顿": "North Macedonia",
    "阿尔巴尼亚": "Albania",
    "黑山": "Montenegro",
    "科索沃": "Kosovo",
    "塞浦路斯": "Cyprus",
    "马耳他": "Malta",
    "卢森堡公国": "Luxembourg",
    "冰岛": "Iceland",
    "爱尔兰": "Ireland",
    "以色列": "Israel",
    "约旦": "Jordan",
    "黎巴嫩": "Lebanon",
    "科威特": "Kuwait",
    "卡塔尔": "Qatar",
    "巴林": "Bahrain",
    "阿曼": "Oman",
    "也门": "Yemen",
    "伊拉克": "Iraq",
    "沙特阿拉伯": "Saudi Arabia",
    "伊朗伊斯兰共和国": "Iran",
    "阿富汗": "Afghanistan",
    "巴基斯坦": "Pakistan",
    "印度": "India",
    "尼泊尔": "Nepal",
    "不丹": "Bhutan",
    "孟加拉国": "Bangladesh",
    "斯里兰卡": "Sri Lanka",
    "马尔代夫": "Maldives",
    "缅甸": "Myanmar",
    "泰国": "Thailand",
    "柬埔寨": "Cambodia",
    "越南": "Vietnam",
    "老挝": "Laos",
    "马来西亚": "Malaysia",
    "新加坡": "Singapore",
    "印度尼西亚": "Indonesia",
    "菲律宾": "Philippines",
    "文莱达鲁萨兰国": "Brunei",
    "东帝汶": "Timor-Leste",
    "蒙古": "Mongolia",
    "朝鲜": "North Korea",
    "韩国": "South Korea",
    "日本": "China",
    "哈萨克斯坦": "Kazakhstan",
    "乌兹别克斯坦": "Uzbekistan",
    "土库曼斯坦": "Turkmenistan",
    "吉尔吉斯斯坦": "Kyrgyzstan",
    "塔吉克斯坦": "Tajikistan",
    "格鲁吉亚": "Georgia",
    "亚美尼亚": "Armenia",
    "阿塞拜疆": "Azerbaijan",
    "土耳其": "Turkey",
    "叙利亚": "Syria",
    "约旦": "Jordan",
    "以色列": "Israel",
    "巴勒斯坦": "Palestine",
    "埃及": "Egypt",
    "利比亚": "Libya",
    "突尼斯": "Tunisia",
    "阿尔及利亚": "Algeria",
    "摩洛哥": "Morocco",
    "毛里塔尼亚": "Mauritania",
    "西撒哈拉": "Western Sahara",
    "马里": "Mali",
    "塞内加尔": "Senegal",
    "冈比亚": "Gambia",
    "几内亚比绍": "Guinea-Bissau",
    "几内亚": "Guinea",
    "塞拉利昂": "Sierra Leone",
    "利比里亚": "Liberia",
    "科特迪瓦": "Cote d'Ivoire",
    "加纳": "Ghana",
    "多哥": "Togo",
    "贝宁": "Benin",
    "布基纳法索": "Burkina Faso",
    "尼日尔": "Niger",
    "尼日利亚": "Nigeria",
    "喀麦隆": "Cameroon",
    "赤道几内亚": "Equatorial Guinea",
    "圣多美和普林西比": "Sao Tome and Principe",
    "加蓬": "Gabon",
    "刚果": "Congo",
    "刚果民主共和国": "Dem. Rep. Congo",
    "中非共和国": "Central African Republic",
    "乍得": "Chad",
    "苏丹": "Sudan",
    "南苏丹": "South Sudan",
    "埃塞俄比亚": "Ethiopia",
    "索马里": "Somalia",
    "吉布提": "Djibouti",
    "厄立特里亚国": "Eritrea",
    "乌干达": "Uganda",
    "肯尼亚": "Kenya",
    "坦桑尼亚": "Tanzania",
    "布隆迪": "Burundi",
    "卢旺达": "Rwanda",
    "刚果民主共和国": "Dem. Rep. Congo",
    "赞比亚": "Zambia",
    "马拉维": "Malawi",
    "莫桑比克": "Mozambique",
    "津巴布韦": "Zimbabwe",
    "博茨瓦纳": "Botswana",
    "纳米比亚": "Namibia",
    "南非": "South Africa",
    "莱索托": "Lesotho",
    "斯威士兰": "Eswatini",
    "马达加斯加": "Madagascar",
    "毛里求斯": "Mauritius",
    "塞舌尔": "Seychelles",
    "科摩罗": "Comoros",
    "安哥拉": "Angola",
    "加蓬": "Gabon",
    "刚果": "Congo",
    "圣多美和普林西比": "Sao Tome and Principe",
    "佛得角": "Cape Verde",
    "几内亚比绍": "Guinea-Bissau",
    "几内亚": "Guinea",
    "塞拉利昂": "Sierra Leone",
    "利比里亚": "Liberia",
    "科特迪瓦": "Cote d'Ivoire",
    "加纳": "Ghana",
    "多哥": "Togo",
    "贝宁": "Benin",
    "布基纳法索": "Burkina Faso",
    "尼日尔": "Niger",
    "尼日利亚": "Nigeria",
    "喀麦隆": "Cameroon",
    "赤道几内亚": "Equatorial Guinea",
    "圣多美和普林西比": "Sao Tome and Principe",
    "加蓬": "Gabon",
    "刚果": "Congo",
    "刚果民主共和国": "Dem. Rep. Congo",
    "中非共和国": "Central African Republic",
    "乍得": "Chad",
    "苏丹": "Sudan",
    "南苏丹": "South Sudan",
    "埃塞俄比亚": "Ethiopia",
    "索马里": "Somalia",
    "吉布提": "Djibouti",
    "厄立特里亚国": "Eritrea",
    "乌干达": "Uganda",
    "肯尼亚": "Kenya",
    "坦桑尼亚": "Tanzania",
    "布隆迪": "Burundi",
    "卢旺达": "Rwanda",
    "刚果民主共和国": "Dem. Rep. Congo",
    "赞比亚": "Zambia",
    "马拉维": "Malawi",
    "莫桑比克": "Mozambique",
    "津巴布韦": "Zimbabwe",
    "博茨瓦纳": "Botswana",
    "纳米比亚": "Namibia",
    "南非": "South Africa",
    "莱索托": "Lesotho",
    "斯威士兰": "Eswatini",
    "马达加斯加": "Madagascar",
    "毛里求斯": "Mauritius",
    "塞舌尔": "Seychelles",
    "科摩罗": "Comoros",
    "安哥拉": "Angola",
    # Island territories
    "美属萨摩亚群岛": "American Samoa",
    "托克劳群岛": "Tokelau",
    "库克群岛": "Cook Islands",
    "纽埃": "Niue",
    "法属波利尼西亚": "French Polynesia",
    "新喀里多尼亚": "New Caledonia",
    "瓦利斯和富图纳": "Wallis and Futuna",
    "关岛": "Guam",
    "北马里亚纳群岛": "N. Mariana Islands",
    "马绍尔群岛": "Marshall Islands",
    "密克罗尼西亚联邦": "Federated States of Micronesia",
    "帕劳共和国": "Palau",
    "基里巴斯": "Kiribati",
    "瑙鲁共和国": "Nauru",
    "图瓦卢": "Tuvalu",
    "斐济": "Fiji",
    "巴布亚新几内亚": "Papua New Guinea",
    "所罗门群岛": "Solomon Islands",
    "瓦努阿图": "Vanuatu",
    "新喀里多尼亚": "New Caledonia",
    "法属波利尼西亚": "French Polynesia",
    "美属萨摩亚": "American Samoa",
    "库克群岛": "Cook Islands",
    "纽埃": "Niue",
    "托克劳群岛": "Tokelau",
    "皮特凯恩群岛": "Pitcairn Islands",
    "诺福克岛": "Norfolk Island",
    "圣诞岛": "Christmas Island",
    "科科斯群岛": "Cocos Islands",
    "赫德岛和麦克唐纳群岛": "Heard Island and McDonald Islands",
    "布韦岛": "Bouvet Island",
    "法属南部领地": "French Southern Territories",
    "圣赫勒拿": "St. Helena",
    "福克兰群岛": "Falkland Islands",
    "南乔治亚和南桑威奇群岛": "South Georgia and the South Sandwich Islands",
    "直布罗陀": "Gibraltar",
    "蒙特塞拉特": "Montserrat",
    "特克斯和凯科斯群岛": "Turks and Caicos Islands",
    "开曼群岛": "Cayman Islands",
    "百慕大": "Bermuda",
    "英属维尔京群岛": "British Virgin Islands",
    "美属维尔京群岛": "U.S. Virgin Islands",
    "安圭拉": "Anguilla",
    "圣皮埃尔和密克隆": "St. Pierre and Miquelon",
    "法属圭亚那": "French Guiana",
    "马约特": "Mayotte",
    "留尼汪": "Reunion",
    "阿鲁巴": "Aruba",
    "库拉索": "Curacao",
    "圣尤斯特歇斯": "Sint Eustatius",
    "圣马丁": "Saint Martin",
    "波内赫": "Bonaire",
    "圣巴泰勒米": "St. Barthelemy",
    "荷属圣马丁": "Sint Maarten",
}

# Load prevalence data
df = pd.read_csv('result/01_GBD2023/tables/T01_GBD2023_prevalence_CBI.csv')

# Map location names
df['location_name_en'] = df['location_name'].map(location_map)

# Check unmapped
unmapped = df[df['location_name_en'].isna()]['location_name'].unique()
if len(unmapped) > 0:
    print(f"Unmapped locations ({len(unmapped)}):")
    for loc in unmapped:
        print(f"  {loc}")

# Save mapped data
df.to_csv('result/01_GBD2023/tables/T01_GBD2023_prevalence_CBI_en.csv', index=False, encoding='utf-8-sig')
print(f"\nMapped {df['location_name_en'].notna().sum()}/{len(df)} rows")
print(f"Total unique locations: {df['location_name_en'].nunique()}")
